version: "3"

services:
  pgsql:
    image: postgres:12
    environment:
      POSTGRES_DB: articledb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpw
    volumes:
      - ".pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  
  app:
    build: .
    environment:
      connectionstring: postgresql://pguser:pgpw@pgsql:5432/articledb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - pgsql